### ISSUE TITLE
HELP! Configure with IAM role

### ISSUE THREAD

**Issue by Apeksh742** [spreadshirt/backstage-plugin-s3#52]
Hi team, can you guide me on what is the correct way to configure this plugin to use IAM role (without passing AWS secret key and access key)? I did implement Custom Credentials Providers which worked for listing buckets but for listing inner contents it uses S3 Client which I am unable to implement. Also, I wanna know is this the correct way? Any help would be appreciated.

**Comment by heyLu** [comment]
Hi @Apeksh742, we don't use AWS S3 internally (we use https://docs.ceph.com/en/) and personally I haven't worked with IAM roles before, so unfortunately I don't really know how this is supposed to work.

Could you provide some more details on why you are unable to implement the S3 Client?  Maybe given some code and more info we can figure out what might be needed to work with AWS's S3.

**Comment by Apeksh742** [comment]
Sure. 

customS3Client.ts - I just removed credentials key in S3 Client so that it picks from my iam profile.

```
export class CustomS3Client implements S3Api  {
    private discoveryApi: DiscoveryService;
    private bucketsProvider: BucketsProvider;

    constructor({ bucketsProvider, discoveryApi }: S3ClientEnvironment) {
        this.bucketsProvider = bucketsProvider;
        this.discoveryApi = discoveryApi;
    }

    private getS3Client(endpoint: string, bucket: string): S3 {
        const data = this.bucketsProvider.getCredentialsForBucket(endpoint, bucket);
        if (!data) {
            throw new Error(`No credentials stored for ${endpoint}/${bucket}`);
        }

        const s3Client = new S3({
            apiVersion: '2006-03-01',
            endpoint: data.endpoint,
            region: data.region,
            forcePathStyle: true,
        });

        return s3Client;
    }

    async listBucketKeys(
        endpoint: string,
        bucket: string,
        continuationToken: string,
        pageSize: number,
        folder: string,
        prefix: string,
    ): Promise<ListBucketKeysResult> {
        const s3Client = this.getS3Client(endpoint, bucket);
        const bucketInfo = this.bucketsProvider.getBucketInfo(endpoint, bucket);
        const output = await s3Client
            .listObjects({
                Bucket: bucket,
                MaxKeys: pageSize,
                Marker: continuationToken,
                Prefix: folder + prefix,
                Delimiter: '/',
            })
            .catch(e => {
                throw new Error(`Error listing keys: ${e.statusCode} ${e.code}`);
            });

        const keys: KeyData[] =
            output.CommonPrefixes?.map(p => ({
                name: p.Prefix?.substring(folder.length) || '',
                isFolder: true,
            })).filter(k => k.name !== '') || [];

        output.Contents?.forEach(c => {
            if (c.Key) {
                keys.push({
                    name: c.Key.substring(folder.length),
                    isFolder: false,
                });
            }
        });

        let totalObjects = bucketInfo?.objects ?? NaN;
        if (totalObjects === 0) {
            totalObjects = keys.length;
        }

        return {
            totalBucketObjects: output.IsTruncated ? totalObjects + 1 : totalObjects,
            keys: keys,
            next: output.NextMarker,
        };
    }
    async headObject(
        endpoint: string,
        bucket: string,
        key: string,
    ): Promise<FetchObjectResult> {
        const s3Client = this.getS3Client(endpoint, bucket);
        const output = await s3Client
            .headObject({
                Bucket: bucket,
                Key: key,
            })
            .catch(e => {
                throw new Error(`Error fetching object: ${e.statusCode} ${e.code}`);
            });

        return {
            name: key,
            bucket: bucket,
            etag: output.ETag?.replace(/"+/g, '') || '',
            lastModified:
                moment(output.LastModified).utc().format('YYYY-MM-DD HH:mm:ss') ||
                'unknown',
            contentLength: output.ContentLength,
            contentType: output.ContentType || '',
            downloadName: key.split('/').pop() || key,
            downloadUrl: await this.getDownloadUrl(endpoint, bucket, key),
        };
    }

    async streamObject(
        endpoint: string,
        bucket: string,
        key: string,
    ): Promise<Readable> {
        const s3Client = this.getS3Client(endpoint, bucket);
        const { Body: body } = await s3Client.send(
            new GetObjectCommand({
                Bucket: bucket,
                Key: key,
            }),
        );

        if (!body) {
            throw new NotFoundError(`Key "${key}" not found in bucket "${bucket}"`);
        }
        if (body instanceof Readable) {
            return body;
        }
        throw new Error('Unexpected stream received');
    }

    private async getDownloadUrl(
        endpoint: string,
        bucket: string,
        key: string,
    ): Promise<string> {
        const s3Url = await this.discoveryApi.getExternalBaseUrl('s3');
        const url = new URL(
            `${s3Url}/stream/${encodeURIComponent(bucket)}/${encodeURIComponent(
                key,
            )}?${new URLSearchParams({ endpoint })}`,
        );
        return url.toString();
    }

}
```

And in s3.ts

```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const allowedBuckets: { [key: string]: string[] } = {};
  const builder = await S3Builder.createBuilder({
    config: env.config,
    logger: env.logger,
    scheduler: env.scheduler,
    discovery: env.discovery,
    identity: env.identity,
    permissions: env.permissions,
    tokenManager: env.tokenManager,
  })
  .setCredentialsProvider(
    new CustomCredentialsProvider(
      [
        {
          endpoint: "https://s3.amazonaws.com/",
          endpointName: "us-east-1-bucket",
          region: "us-east-1",
        }
      ],
      env.logger,
      allowedBuckets
    )
  )
  .setClient(new CustomS3Client())
  .useMiddleware()

  const { router } = await builder.build();
  return router;
}
```

Error message is: 
```
Argument of type 'CustomS3Client' is not assignable to parameter of type 'S3Client'.
  Types have separate declarations of a private property 'discoveryApi'.ts
```

The doc says to implement S3Api but is expecting S3Client maybe this is problem.

**Comment by heyLu** [comment]
> The doc says to implement S3Api but is expecting S3Client maybe this is problem.

Yeah, I'd say that's the issue, `setClient` only accepts the built-in `S3Client` at the moment, but should probably accept an `S3Api`: https://github.com/spreadshirt/backstage-plugin-s3/blob/00b1ffa7fc41dfafa623a8480d72eb4007194e45/plugins/s3-viewer-backend/src/service/S3Builder.ts#L119

@ivangonzalezacuna, what do you think?  I fixed it in https://github.com/spreadshirt/backstage-plugin-s3/pull/53, which was rather easy, it seems like we just missed making `setClient` accept the correct type.

**Comment by ivangonzalezacuna** [comment]
Hi @Apeksh742 . I have just merged the fix and released a new version of the package. Can you try it out and let us know if the issue is fixed?

**Comment by Apeksh742** [comment]
Hi guys, thanks for the release and fixing that.
I am still not able to achieve it. The issue I am having is setClient needs a s3clientEnvironment which needs discoveryApi & BucketsProvider. I am not sure how to pass bucketsProvider to it.
s3.ts
```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const allowedBuckets: { [key: string]: string[] } = {};
  const refreshInterval: HumanDuration | undefined = undefined;
  const bucketsProvider: BucketsProvider =  undefined
  const s3ClientEnvironment: S3ClientEnvironment = {discoveryApi: env.discovery, bucketsProvider: bucketsProvider };
  const builder = await S3Builder.createBuilder({
    config: env.config,
    logger: env.logger,
    scheduler: env.scheduler,
    discovery: env.discovery,
    identity: env.identity,
    permissions: env.permissions,
    tokenManager: env.tokenManager,
  })
  .setCredentialsProvider(
    new CustomCredentialsProvider(
      [
        {
          endpoint: "https://s3.amazonaws.com/",
          endpointName: "us-east-1-bucket",
          region: "us-east-1",
        }
      ],
      env.logger,
      allowedBuckets
    )
  )
  .setClient(new CustomS3Client(s3ClientEnvironment))
  .useMiddleware()

  const { router } = await builder.build();
  return router;
}
```
The Custom S3 Client is same as I have shown above. 
My use case it to just remove credentials while creating S3 Client. So if there is any other way please suggest it.
https://github.com/spreadshirt/backstage-plugin-s3/blob/9fe5c851b03dae9f54dcb8755903dd556e3b08af/plugins/s3-viewer-backend/src/service/S3Api.ts#L78C7-L81C9

**Comment by ivangonzalezacuna** [comment]
Hm, that's unfortunate. I'll reopen the issue and try to find a solution.

**Comment by Apeksh742** [comment]
Hi @heyLu @ivangonzalezacuna , I was finally able to make it work by creating a custom bucketsProvider too.
I want to suggest a couple of changes related to types if possible
Making credentials parameter optional in type [S3Platform](https://github.com/spreadshirt/backstage-plugin-s3/blob/9fe5c851b03dae9f54dcb8755903dd556e3b08af/plugins/s3-viewer-backend/src/types.ts#L11C3-L11C14)
and I was not able to import type BucketDetailsFilters.
Thanks.

**Comment by ivangonzalezacuna** [comment]
Ok. First thought about the issue you were having with the `CustomS3Client`. I think the issue is that you were referencing the `S3Client`, but you should now implement the interface `S3Api` ([link](https://github.com/spreadshirt/backstage-plugin-s3/blob/main/plugins/s3-viewer-backend/src/service/S3Api.ts#L18)). If you do so, you can initialize the client the way you want, without needing to use the `S3ClientEnvironment`, which is needed for initializing the default S3Client. Then, you would only need to implement the 3 required methods. 

However, the bucketsProvider will be most likely needed inside. So what about adding a new method to the `S3Api` called `setBucketsProvider`, which could be injected directly when running the `build()`.

Regarding the optional credentials, I will need to try out if that is easy and doesn't require too many changes.

And for what do you need the types from `ListBucketsFilter.tsx`? So far, the currently 2 exported ones (`createS3ViewerBucketsConditionalDecision` and `s3ViewerBucketConditions`) are more than enough for outside. And all the permission checks are done inside the router function.

**Comment by ivangonzalezacuna** [comment]
@Apeksh742, I've just added the change I mentioned to inject the bucketsProvider in custom clients if needed. I will release it in a while.

Now I'm thinking about what is the best approach for the credentials setup. First of all, is this IAM setup something widely used and that could be interesting for others? In such case, I would suggest extending the s3 plugin to support this as well. How to do that?

I would suggest creating a new `credentials-provider` for this new option, which doesn't require credentials at all, then integrating this new config in the `config.d.ts` file, and extend the method `getCombinedCredentialsProvider` ([link](https://github.com/spreadshirt/backstage-plugin-s3/blob/main/plugins/s3-viewer-backend/src/credentials-provider/index.ts)) with this new provider.

Then, I would create the new S3 Client required for this IAM method. Probably in a new folder called `clients` for example. And change the builder to use a similar function as the credentialsProvider to fetch the correct client depending on the option used.

With this changes, you could then simply configure your `app-config.yaml` with something like:
```yaml
s3:
  bucketLocatorMethods:
    - type: iam # Or the name that would match better here, not sure
      platforms:
        - endpoint: http://127.0.0.1:8080
          name: test
          region: 'us-east-1'
```

And the builder will pick everything up for you automatically, and potentially for others as well if this is used in other companies.

Would this be a good idea? Let us know. It would we cool if you'd like to contribute this changes, and I could support if you have questions. If not, I could try adding it myself, but I'd ask you to test it, since I don't know how to try this things out with IAM roles.

**Comment by Apeksh742** [comment]
Yes, the issue was the constructor of customS3Client implementing S3Api required a bucketsProvider so I had to create an object with CustomBucketsProvider in order to pass it.

So I was implementing same original BucketsProvider, but it was using these `BucketDetailsFilters`, `matches` which I was not able to import.

**Comment by ivangonzalezacuna** [comment]
Oh well, that's indeed true. The bucketsProvider uses 2 types from the permissions folder that are not exported. Might be worth exporting them.

And what about the suggestion I did about integrating the IAM Roles setup inside the plugin? If your current solution is standard, it might be helpful for others as well.

**Comment by Apeksh742** [comment]
Yeah, I checked it looks good. I feel currently it is too coupled. I wanted to use default bucketsProvider in first place but did not have that freedom.

**Comment by Apeksh742** [comment]
Yes, this will be awesome as it is a very common requirement and recommended approach from AWS in first place.

**Comment by ivangonzalezacuna** [comment]
Alright. So next week I will try to schedule some time to design this changes. If I understood from your comments above, to pick the IAM role we just need to skip the `credentials`, or set them to undefined, isn't it? In such case it could be even simpler. But I'll need to check that nothing breaks with these changes

**Comment by ivangonzalezacuna** [comment]
Ok, no problem.

I'd say, to test it faster, you could just copy the `s3-viewer-backend` folder inside your `plugins` folder and run `yarn install`. This way it will pick your local folder instead. There are other ways, but usually there are some issues, specially using the backstage plugins.

**Comment by Apeksh742** [comment]
Hi @ivangonzalezacuna, I have tried the PR and it is working fine without custom credentials provider & client now.  Just there is one small typo in **platforms** at  https://github.com/spreadshirt/backstage-plugin-s3/blob/d767b973975830350f39fc665000c29ff187a881/plugins/s3-viewer-backend/src/credentials-provider/IAMRoleCredentialsProvider.ts#L29C24-L29C34 otherwise it works great out of the box.
